name: Auto cancel
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # 同一グループのワークフローが実行中ならキャンセル
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.workflow }}-${{ github.ref }}" # Auto cancel-refs/pull/7/merge のような文字列になる
      - run: sleep 20 # (20秒) スリープ
