name: Auto patch merge
on: pull_request
permissions: {}
jobs:
  merge:
    if: ${{ github.event_name == 'dependabot[bot]'}}  # DependabotのPRのみ
    runs-on: ubuntu-latest
    permissions:                                      # マージに必要なパーミッション
      contents: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       # Github CLIのクレデンシャル
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - id: meta                                      # 依存関係のメタデータを取得
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # v3            # 条件分岐でパッチバージョンかチェック
      - if: ${{ steps.meta.outputs.update-type == 'version-update:semver-patch' }}
        run: |                                        # Github CLIで承認とマージ 
          gh pr review "${GITHUB_HEAD_REF}" --approve
          gh pr merge "${GITHUB_HEAD_REF}" --merge --auto
