name: Auto cancel
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # 同一グループのワークフローが実行中ならキャンセル
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.workflow }}-${{ github.ref }}"
      - run: sleep 120 # 2分(120秒) スリープ
