name: Bad variables
on: pull_request
jobs:
  print:
    runs-on: ubuntu-latest
    steps: # そのままタイトルにセットしてしまうとactions実行時にスクリプトインジェクションの脆弱性が生じる
      - run: echo "${{ github.event.pull_request.title }}"
