name: Bash tracing
on: workflow_dispatch
permissions: {}
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |      # Bashのトレーシングオプションを有効化　し、実行したコマンドをログ出力
          set -x
          date
          hostname
