name: Concurrency
on: workflow_dispatch
concurrency: ${{ github.workflow }}
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.workflow}}
      - run: sleep 120 # 2分(120秒) スリープ
  