name: Conditions
on: workflow_dispatch
permissions: {}
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '8') }} # ワークフロー実行IDで分岐
