name: Conditions workflow
on: workflow_dispatch
permissions: {}
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octcat' }} # octcatアカウント以外は実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
