name: Conftest
on: pull_request
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Run Conftest
        run: | # ポリシーファイルのパスを指定し、Conftestでワークフローファイルを検証
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          openpolicyagent/conftest test --policy policy/ .github/workflows/
