name: Conftest
on: pull_request
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Run Conftest
        run: | # ポリシーファイルのパスを指定し、Conftestでワークフローファイルを検証
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          openpolicyagent/conftest test --policy policy/ .github/workflows/
