name: Conftest
on: pull_request
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Run Conftest
        run: | # ポリシーファイルのパスを指定し、Conftestでワークフローファイルを検証
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          openpolicyagent/conftest test --policy policy/ .github/workflows/
