name: Contexts
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # githubコンテキストの参照
    steps:
      - run: |
          echo "実行ユーザ ${ACTOR}"
          echo "実行ユーザ ${GITHUB_ACTOR}" # デフォルト環境変数の参照
          echo "ワークフローの実行ID ${{ github.run_id}}"
          echo "プルリクエストのソースブランチ ${GITHUB_HEAD_REF}"
          echo "ステップのワーキングディレクトリ ${{ github.workspace }}"
          echo "リポジトリ名 ${{ github.repository }}"
          echo "リポジトリのオーナー名 ${{ github.repository_owner }}"
          echo "トリガーになったイベント ${{ github.event }}" # eventはオブジェクト(ダンプして値をみる)
          echo "ランナーの名前 ${{ runner.name }}"
          echo "OS ${{ runner.os }}"
          echo "CPUアーキテクチャ ${{ runner.arch }}"
          echo "一時ディレクトリのパス ${{ runner.temp }}"
          echo "インストール済みツールのディレクトリパス ${{ runner.tool_cache }}"
          echo "デバッグログ ${{ runner.debug }}"
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
