name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "実行ユーザ ${{ github.actor }}" # githubコンテキストの参照
          echo "ワークフローの実行ID ${{ github.run_id}}"
          echo "プルリクエストのソースブランチ ${{ github.head_ref }}"
          echo "ステップのワーキングディレクトリ ${{ github.workspace }}"
          echo "リポジトリ名 ${{ github.repository }}"
          echo "リポジトリのオーナー名 ${{ github.repository_owner }}"
          echo "トリガーになったイベント ${{ github.event }}" # eventはオブジェクト(ダンプして値をみる)
          echo "ランナーの名前 ${{ runner.name }}"
          echo "OS ${{ runner.os }}"
          echo "CPUアーキテクチャ ${{ runner.arch }}"
          echo "一時ディレクトリのパス ${{ runner.temp }}"
          echo "インストール済みツールのディレクトリパス ${{ runner.tool_cache }}"
          echo "デバッグログ ${{ runner.debug }}"
