name: Convert
on: workflow_dispatch
env:
  TIMEOUT: 1                                         # 環境変数はstring型となる
permissions: {}
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120
        timeout-minutes: ${{ fromJSON(env.TIMEOUT)}} # string型をnumber型へ変換
