name: Cross repo
on: push
permissions: {}
env:
  TARGET_REPO: github-terraform
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - id: create
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          repositories: ${{ env.TARGET_REPO }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          repository: ${{ github.repository_owner }}/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
      - run: cat "${TARGET_REPO}/README.md"
