name: Environment Variables
on: workflow_dispatch
permissions: {}
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ env.BRANCH }}
