name: Environment Variables
on: workflow_dispatch
permissions: {}
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - run: echo "${BRANCH}"
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          ref: ${{ env.BRANCH }}
