name: Generate Functions
on: workflow_dispatch
permissions: {}
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Generate Functions
        run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}', 'Hi', 'World') }} #フォーマット
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} #カンマで結合
