name: Generate Functions
on: workflow_dispatch
permissions: {}
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Generate Functions
        run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}', 'Hi', 'World') }} #フォーマット
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} #カンマで結合
