name: GITHUB_ENV
on: workflow_dispatch
permissions: {}
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "RESULT=Hello" >> "${GITHUB_ENV}" # GITHUB_ENVへ書き出し
      - run: echo "${RESULT}"                       # 通常の環境変数として参照
