name: Hash functions
on: workflow_dispatch
permissions: {}
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
