name: Hello
on: workflow_dispatch
permissions: {}
jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
     - run: |
        tree -a
        echo "Hello, World!"
     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
       with:
          ref: main
