name: Job summaries
on: workflow_dispatch
permissions: {}
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: | # マークダウンテキストをジョブサマリーへ出力
          {
            echo "## Example Title :rocket:"
            echo "- first line"
            echo "- second line"
          } >> "${GITHUB_STEP_SUMMARY}"
