name: JSON functions
on: workflow_dispatch
permissions: {}
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} # githubコンテキストをJSON文字列でダンプ
