name: Literals
on: workflow_dispatch
permissions: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_NULL: ${{ null }}      # null型
          LITERAL_BOOLEAN: ${{ true }}   # boolean型
          LITERAL_NUMBER: ${{ 1234 }}    # number型
          LITERAL_STRING: ${{ 'Hello' }} # string型
          LITERAL_OMIT_STRING: World     # 省略記法
