name: Old
on: workflow_dispatch
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6 # 古いバージョンを意図的に指定
        with:
          go-version: 1.25
