name: Static Application Security Testing (SAST)
on: pull_request
permissions: {}
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #     - run: pip install bandit # Banditのインストール
  #     - run: bandit -r .        # BanditでPythonのコードスキャン
  test:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Run Gosec Security Scanner
        uses: securego/gosec@caf8857bbd3276599d0176b0528e9712bb0b5bec # master
        with:
          args: ./...
