name: Secrets
on: workflow_dispatch
permissions: {}
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ secrets.PASSWORD }} # Secretsの参照(忘れずに中間環境変数を経由させる)
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # CAUTION: 先頭1文字とそれ以外の文字列を表示しようとすると出来てしまうので注意
