name: Sequential jobs
on: workflow_dispatch
jobs:
  first: # 依存ジョブがないので最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second: # firstジョブの後に実行される
    runs-on: ubuntu-latest
    needs: [first] # needsキーへ依存するfirstジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Second job"
  third: # secondジョブの後に実行される
    runs-on: ubuntu-latest
    needs: [second] # needsキーへ依存するsecondジョブのIDを指定
    steps:
      - run: sleep 10 && echo "Third job"
